export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

export const ADDING_DATA_START = "ADDING_DATA_START";
export const ADDING_DATA_SUCCESS = "ADDING_DATA_SUCCESS";
export const ADDING_DATA_FAILURE = "ADDING_DATA_FAILURE";

export const UPDATING_DATA_START = "UPDATING_DATA_START";
export const UPDATING_DATA_SUCCESS = "UPDATING_DATA_SUCCESS";
export const UPDATING_DATA_FAILURE = "UPDATING_DATA_FAILURE";

export const DELETING_DATA_START = "DELETING_DATA_START";
export const DELETING_DATA_SUCCESS = "DELETING_DATA_SUCCESS";
export const DELETING_DATA_FAILURE = "DELETING_DATA_FAILURE";
